version: '2'
services:

  php-fpm:
    build:
      context: ./docker
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    # environment:
    #   - "DB_PORT=3306"
    #   - "DB_HOST=database"

  nginx:
    build:
      context: ./docker
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - php-fpm
    ports:
      - 80:80
      - 443:443